CREATE TABLE IF NOT EXISTS copilot_usage (bucket TEXT PRIMARY KEY, requests INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS invoice_receipts (invoice_id TEXT PRIMARY KEY, tx_hash TEXT NOT NULL UNIQUE, chain_id INTEGER NOT NULL, recorded_at TIMESTAMPTZ NOT NULL DEFAULT now());
