import Link from "next/link";
import Image from "next/image";
import {GhostShell} from "@/components/ghost/GhostShell";
import {GHOST_DEMO} from "@/lib/ghost/evidence";

export default function GhostPage(){return <GhostShell title="Phone off. Permission on." landing>
  <section className="ghost-hero" aria-labelledby="ghost-title">
    <div className="ghost-hero-copy"><p className="ghost-kicker"><span aria-hidden="true"/>LESS SCREEN. MORE LIFE.</p><h1 id="ghost-title">Phone off.<br/><em>Permission on.</em></h1><p className="ghost-hero-description">Reserve tokens online. Carry a limited payment permission on paper. Your merchant claims once.</p><div className="ghost-hero-actions"><Link className="ghost-primary-link" href="/ghost/create">Issue a voucher <span aria-hidden="true">↗</span></Link><Link className="ghost-secondary-link" href="/ghost/merchant">I’m a merchant <span aria-hidden="true">↗</span></Link></div><p className="ghost-hero-note">BSC Testnet · MockUSDC has no cash value</p></div>
    <div className="ghost-hero-visual"><div className="ghost-art-label"><span>THE PHONE CAN WAIT.</span><span aria-hidden="true">↘</span></div><Image src="/illustrations/hero-success.jpg" width={1000} height={1000} alt="Illustrated Indonesian merchant holding a printed code outside her stall" sizes="(max-width:767px) calc(100vw - 48px), 480px" loading="eager" fetchPriority="high" className="ghost-hero-art"/><div className="ghost-art-caption"><span className="ghost-caption-dot" aria-hidden="true"/><span>Buyer offline.<br/><strong>Merchant online.</strong></span><span className="ghost-stamp">ONE<br/>CLAIM ↗</span></div></div>
  </section>
  <section className="ghost-proof-strip" aria-label="Recorded testnet evidence"><div><span className="ghost-proof-icon" aria-hidden="true">↗</span><p><small>RECORDED ON BSC TESTNET</small><strong>5 MockUSDC. Claimed once.</strong></p></div><a href={`https://testnet.bscscan.com/tx/${GHOST_DEMO.redeemTx}`} target="_blank" rel="noopener noreferrer">Inspect the transaction <span aria-hidden="true">↗</span></a></section>
  <section className="ghost-how" aria-labelledby="ghost-how-title"><div className="ghost-section-head"><p className="page-eyebrow">FROM WALLET TO PAPER</p><h2 id="ghost-how-title">Three moves. Then go.</h2></div><div className="ghost-steps"><article><span>01 / PREPARE</span><h3>Give it limits.</h3><p>Pick the merchant, amount and expiry. Sign and reserve your test tokens.</p></article><article><span>02 / HAND OVER</span><h3>Take it off-screen.</h3><p>Print or privately share the code. Your wallet key stays with you.</p></article><article><span>03 / CLAIM</span><h3>One claim. Done.</h3><p>The online merchant redeems. Unused? Reclaim it after expiry.</p></article></div></section>
  <footer className="ghost-footer"><details className="ghost-limit-details"><summary>Know the limits <span aria-hidden="true">+</span></summary><p>The buyer prepares online; the merchant needs internet and TEST BNB. Handing over the code lets its named merchant claim immediately. Delivery is not guaranteed. This is not QRIS or a real-money payment. Physical phone-off testing is still pending.</p></details><Link href="/demo" className="ghost-secondary-link">Explore the demo <span aria-hidden="true">↗</span></Link></footer>
</GhostShell>;}
